### ISSUE TITLE
Broken page: Pure CSS scrolling shadows with background-attachment: local

### ISSUE THREAD

**Issue by jvdl** [LeaVerou/lea.verou.me#80] opened 2024-12-17 04:07 UTC
### Page URL:

https://lea.verou.me/blog/2012/04/background-attachment-local/

### Old URL:

https://lea0.verou.me/2012/04/background-attachment-local/

### Did this page work in the previous website?

Yes

### What issues do you see?

Broken image(s)

### Description of issues

Some time ago an absolute disaster has befallen the web. placekitten.com is no longer available and this has broken the Dabblet example on this page.

Thankfully, a good soul has made a replacement service called placecats.com. It doesn't have the same variety of cats, but they're still cats, so we'll allow it.

**Comment by DmitrySharabin** [comment] 2024-12-24 13:10
@LeaVerou, I would love to fix this page. However, the issue is in [the corresponding Gist](https://gist.github.com/LeaVerou/2494566#file-dabblet-css-L9), which I can't change or send a PR for.

**Comment by LeaVerou** [comment] 2024-12-25 00:48
Ah, got it. Should be fixed now, thank you both!

**Closed by LeaVerou** 2024-12-25 00:48 UTC
Labels: broken-page
