### ISSUE TITLE
Page regression: Blog

### ISSUE THREAD

**Issue by davidmead** [LeaVerou/lea.verou.me#14] opened 2023-07-22 18:52 UTC
### Page URL:

https://lea.verou.me/blog/

### Did this page work in the previous website?

Yes

### What issues do you see?

Other

### Description of issues

Doesn't seem to have an RSS feed.

**Comment by LeaVerou** [comment] 2023-07-23 10:54
Duplicate of #13. Could you please vote there?

**Closed by LeaVerou** 2023-07-23 10:54 UTC
Labels: duplicate, broken-page
